export const questions = [
  "What's a skill you've been meaning to learn?",
  "If you could travel anywhere in the world right now, where would you go and why?",
  "What fictional world would you love to visit, and why?",
  "What's the most interesting fact you've learned recently?",
  "What's a movie or book that changed your perspective on life?",
  "What's the best piece of advice you've ever received?",
  "If you could have a superpower, what would it be and how would you use it?",
  "What's a song that always lifts your spirits?",
  "What's the most beautiful place you've ever seen?",
  "Describe your dream home in three words.",
  "What's a cause you're passionate about?",
  "What's the most underrated food in your opinion?",
  "If you could invent something, what would it be?",
  "What historical event would you love to have witnessed firsthand?",
  "What's a childhood memory you cherish most?",
  "What are you currently reading or watching that you'd recommend?",
  "What's a fear you've overcome?",
  "What's the most creative way you've ever solved a problem?",
  "What's your favorite board game or card game, and why?",
  "If you could have one magical talent, what would it be?",
  "What's the best way to spend a rainy day?",
  "What's a tradition you love in your culture?",
  "Describe your ideal weekend getaway.",
  "What's the best compliment you've ever received?",
  "What fictional character do you identify with most, and why?",
  "If you could learn a new language fluently, which would it be?",
  "What's your favorite way to de-stress after a long day?",
  "What's the most inspiring story you've ever heard?",
  "What's one thing you're really good at, and how did you develop that skill?",
  "What's a quote that resonates deeply with you?",
  "What historical mystery would you love to see solved?",
  "If you could bring back one extinct animal, which would it be and why?",
  "What's the most meaningful gift you've ever given or received?",
  "What's a random act of kindness you've witnessed that brightened your day?",
  "What's the craziest dream you've ever had?",
  "If you could have a pet that wasn't real, what would it be?",
  "What's the best piece of life advice you'd give to your younger self?",
  "What does your ideal world look like?",
  "What's one thing you're looking forward to in the future?",
  "What's the most unique or interesting thing you've ever collected?",
  "If you could have a time machine, would you travel to the past or the future, and why?",
  "What's the best way to spend a day off with no plans?",
  "What's a small change you've made in your life that's had a big impact?",
  "What's the most delicious meal you've ever had?",
  "What's a challenge you're currently facing, and how are you tackling it?",
  "What's the best concert or live performance you've ever been to?",
  "What's a talent you wish you possessed?",
  "What are you most grateful for in your life?",
  "What's the most important lesson you've learned from a mistake?",
  "If you could eliminate one thing from the world, what would it be and why?",
];
